In [1]:
import numpy as np

In [2]:
a = np.array([10,20,30])
a

array([10, 20, 30])

In [4]:
a[0:2]

array([10, 20])

In [5]:
a = np.array([[10,20,30],[100,200,300]])
a

array([[ 10,  20,  30],
       [100, 200, 300]])

In [7]:
a[0,2]

30

In [10]:
a.mean(1)

array([ 20., 200.])